### ISSUE TITLE
保证所有软件能够正常使用

### ISSUE THREAD

**Issue by jeffok** [BaiqingL/OpenWRT-GL.iNet-Slate-AR750S#2]
不能ssh 登陆

**Comment by BaiqingL** [comment]
目前没有支持，我明天会再整理一些'软件

**Comment by jeffok** [comment]
好的，到时候再更新一下，需要安装软件，不然使用起来很不方便

**Comment by jeffok** [comment]
内核建议可以更新到5.4内核了

**Comment by jeffok** [comment]
v2 + ray  协议也没有了。。

**Comment by BaiqingL** [comment]
目前的问题原因已经找到，因为在编译时压缩与简化导致Dropbear崩溃，但是如果不经过这些步骤系统镜像的体积太大（18MB）。目前只能停止支持一些插件，优先考虑helloworld等

**Comment by BaiqingL** [comment]
加入了更新文件，可以通过Web控制界面刷入固件来修复SSH
