### ISSUE TITLE
更新周期 

### ISSUE THREAD

**Issue by jeffok** [BaiqingL/OpenWRT-GL.iNet-Slate-AR750S#3]
您好，用了两个星期左右，第一次的固件比较稳定且使用起来挺方便，不知道你这边什么时候会再次更新，
helloword在实际使用的时候并没有passwall方便，ssr-plus占用资源比较大。这个小盒子性能很不错，结果smartdns+passwall 可能达到非常好的性能。
是否可以提供一个编译的规则及配置文件。这样我们在使用的时候可以自己进行编译。

**Comment by jeffok** [comment]
https://github.com/kenzok8/openwrt-packages.  这个仓库里边有需要的软件，看看能不能搞成ipk

**Comment by BaiqingL** [comment]
好的，我会研究，谢谢你的建议

**Comment by jeffok** [comment]
自己编译了，关闭
